services:
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/atlas-game
    depends_on:
      - backend
